/****************************
DISRUPTIVE CLASSROOM BEHAVIOR 
****************************/

/*
A1-2-4-5BEHVR
G6-7BEHVR
M6-7BEHVR
N6-7BEHVR

A4KBEHV
G7DISRUP
M7DISRUP
*/

replace A1BEHVR = .b if A1BEHVR == -9 // NOT ASCERTAINED

replace A2BEHVR = .a if A2BEHVR == -1 // NOT APPLICABLE
replace A2BEHVR = .b if A2BEHVR == -9 // NOT ASCERTAINED

replace A4BEHVR = .b if A4BEHVR == -9 // NOT ASCERTAINED

replace A5BEHVR = .b if A5BEHVR == -9 // NOT ASCERTAINED

replace G6BEHVR = .b if G6BEHVR == -9 // NOT ASCERTAINED
replace G7BEHVR = .b if G7BEHVR == -9 // NOT ASCERTAINED

replace M6BEHVR = .b if M6BEHVR == -9 // NOT ASCERTAINED
replace M7BEHVR = .b if M7BEHVR == -9 // NOT ASCERTAINED

replace N6BEHVR = .b if N6BEHVR == -9 // NOT ASCERTAINED
replace N7BEHVR = .b if N7BEHVR == -9 // NOT ASCERTAINED

gen GMN6BEHVR = (G6BEHVR+M6BEHVR+N6BEHVR)/3
replace GMN6BEHVR = (G6BEHVR+M6BEHVR)/2 if N6BEHVR >= .
replace GMN6BEHVR = (G6BEHVR+N6BEHVR)/2 if M6BEHVR >= .
replace GMN6BEHVR = (M6BEHVR+N6BEHVR)/2 if G6BEHVR >= .
replace GMN6BEHVR = G6BEHVR if M6BEHVR >= . & N6BEHVR >= .
replace GMN6BEHVR = M6BEHVR if G6BEHVR >= . & N6BEHVR >= .
replace GMN6BEHVR = N6BEHVR if G6BEHVR >= . & M6BEHVR >= .

gen GMN7BEHVR = (G7BEHVR+M7BEHVR+N7BEHVR)/3
replace GMN7BEHVR = (G7BEHVR+M7BEHVR)/2 if N7BEHVR >= .
replace GMN7BEHVR = (G7BEHVR+N7BEHVR)/2 if M7BEHVR >= .
replace GMN7BEHVR = (M7BEHVR+N7BEHVR)/2 if G7BEHVR >= .
replace GMN7BEHVR = G7BEHVR if M7BEHVR >= . & N7BEHVR >= .
replace GMN7BEHVR = M7BEHVR if G7BEHVR >= . & N7BEHVR >= .
replace GMN7BEHVR = N7BEHVR if G7BEHVR >= . & M7BEHVR >= .
