/****************
PUPIL ABSENTEEISM 
****************/

/*
A2-4-5ABSEN

G6ABSEN
M6ABSEN
N6ABSEN

G7ABSENT
M7ABSENT
N7ABSENT

U2-4ABSN
A4KABSE
*/

replace A2ABSEN = .a if A2ABSEN == -1 // NOT APPLICABLE
replace A2ABSEN = .b if A2ABSEN == -9 // NOT ASCERTAINED

replace A4ABSEN = .b if A4ABSEN == -9 // NOT ASCERTAINED

replace A5ABSEN = .b if A5ABSEN == -9 // NOT ASCERTAINED

replace G6ABSEN = .b if G6ABSEN == -9 // NOT ASCERTAINED

replace M6ABSEN = .b if M6ABSEN == -9 // NOT ASCERTAINED
replace M6ABSEN = .d if M6ABSEN == -8 // DON'T KNOW

replace N6ABSEN = .b if N6ABSEN == -9 // NOT ASCERTAINED
replace N6ABSEN = .d if N6ABSEN == -8 // DON'T KNOW

gen GMN6ABSEN = (G6ABSEN+M6ABSEN+N6ABSEN)/3
replace GMN6ABSEN = (G6ABSEN+M6ABSEN)/2 if N6ABSEN >= .
replace GMN6ABSEN = (G6ABSEN+N6ABSEN)/2 if M6ABSEN >= .
replace GMN6ABSEN = (M6ABSEN+N6ABSEN)/2 if G6ABSEN >= .
replace GMN6ABSEN = G6ABSEN if M6ABSEN >= . & N6ABSEN >= .
replace GMN6ABSEN = M6ABSEN if G6ABSEN >= . & N6ABSEN >= .
replace GMN6ABSEN = N6ABSEN if G6ABSEN >= . & M6ABSEN >= .

replace G7ABSENT = .b if G7ABSENT == -9 // NOT ASCERTAINED
replace M7ABSENT = .b if M7ABSENT == -9 // NOT ASCERTAINED
replace N7ABSENT = .b if N7ABSENT == -9 // NOT ASCERTAINED
